auth:
  dbit:
    url: "wss://www.deribit.com/ws/api/v2"
    client_id: "---"
    client_secret: "----"
    refresh_token: null 

  kraken:
    api_key: "---"
    api_secret: "---=="
    

  htx:
    client_id: "---"
    client_secret: "---"

  binance:
    url: "wss://data-stream.binance.vision"





currency: "BTC"
